import pytest
from src.tools.general.handler import handle_general_query, CAPABILITIES_TEMPLATE


def test_exact_greeting_match():
    # Scenario: User sends a simple standard greeting
    user_input = "سلام خسته نباشید"
    response = handle_general_query(user_input)
    assert response == CAPABILITIES_TEMPLATE


def test_embedded_greeting_match():
    # Scenario: User embeds a greeting word within a simple sentence
    user_input = "درود بر شما روز خوش"
    response = handle_general_query(user_input)
    assert response == CAPABILITIES_TEMPLATE


def test_llm_small_talk_fallback():
    # Scenario: User asks an off-topic open question that should trigger LLM guidance
    user_input = "تو دقیقا کی هستی و چیکار میکنی؟"
    response = handle_general_query(user_input)
    
    # Assertions to ensure LLM followed the prompt instructions
    assert response is not None
    assert len(response) > 0
    # The response should be dynamically generated by LLM, not the exact static template
    assert response != CAPABILITIES_TEMPLATE